container: aozora0000/jenkins-ci-php:5.4
steps:
    - name: boxインストール
      code: curl -LSs https://box-project.github.io/box2/installer.php | php
    - name: composerインストール
      code: composer self-update && composer install
    - name: PHPUNIT起動
      code: phpunit
    - name: ビルドテスト
      code: php -d phar.readonly=Off box.phar build && ls dockerbuilder.phar
    - name: 掃除
      code: rm -f dockerbuilder.phar
notify:
    - service: idobata
      token: $IDOBATA_TOKEN
