language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
    - curl -LSs https://box-project.github.io/box2/installer.php | php
install:
    - composer self-update && composer install
script:
    - phpunit
    - php box.phar build
